workflows:
  android-simple:
    name: Android Simple Build
    max_build_duration: 60
    environment:
      java: 11  # ⚠️ PASTI Java 11

    scripts:
      - name: Build Debug APK
        script: |
          # Guna gradlew (wrapper) bukan gradle
          ./gradlew clean assembleDebug
          
          # Verify APK exists
          if [ -f "app/build/outputs/apk/debug/app-debug.apk" ]; then
            echo "✅ APK created successfully!"
          else
            echo "❌ APK not found!"
            ls -la app/build/outputs/apk/debug/
            exit 1
          fi

    artifacts:
      - app/build/outputs/apk/debug/*.apk
